#!/usr/bin/env bash

#------------------------------------------------------------------------------
# FUNCTIONS
#------------------------------------------------------------------------------

function svc_ctrl () {
  # @TODO find better way to consume previously defined vars
  REDHAT_RELEASE=$(grep -Eo "[0-9.]+" /etc/redhat-release \
    | awk -F. '{print $1 "." $2}');
  # determine controller
  if [[ $(echo "${REDHAT_RELEASE}>=7.0" | bc) == 0 ]]; then
    ctrl='service';
  else
    ctrl='systemctl';
  fi
  # signal service
  case $1 in
    start|stop|reload)
      $ctrl $1 $2;
      ;;
    *)
      echo "==> ERROR: unsupported request '$ctrl $1 $2'";
      exit 1;
      ;;
  esac
}

function usage () {
  cat << EOF
  Usage: $0 -(i|u)

    -i        install nginx from source [default]
    -u        uninstall nginx
    -v        install specific nginx version [default: 1.8.0]

EOF
}

#------------------------------------------------------------------------------
# ARGUEMENTS
#------------------------------------------------------------------------------

while getopts :iuv: FLAG; do
  case $FLAG in
    i|install)
      app='install';
      ;;
    u|uninstall)
      app='uninstall';
      ;;
    v|version)
      ver=$OPTARG;
      ;;
    *)
      usage;
      exit 0;
      ;;
  esac
done
shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------

NGINX_DEFAULT='1.8.0';
NGINX_PREFIX='/etc/nginx';
SRC_DIR='/usr/local/src';
HOME=`dirname $(realpath $0)`;

#------------------------------------------------------------------------------
# MAIN
#------------------------------------------------------------------------------

# verify os
if [ -f /etc/redhat-release ]; then
  REDHAT_RELEASE=$(grep -Eo "[0-9.]+" /etc/redhat-release \
    | awk -F. '{print $1 "." $2}');
else
  echo "==> ERROR: Unsupported operating system";
  exit 1;
fi

# set nginx release
if [ ! -z ${ver} ]; then
  NGINX_RELEASE=${ver};
else
  NGINX_RELEASE=${NGINX_DEFAULT};
fi

# default install nginx
if [ -z ${app} ]; then
  app='install';
fi

# nginx app install/uninstall
case ${app} in
  install)
    # install prerequsites
    echo "==> Installing Prerequsites";
    yum update -y && yum clean all;
    yum install -y bc curl gcc gcc-c++ make openssl-devel pcre pcre-devel \
      perl tar wget zlib-devel;
    # create nginx user
    echo "==> Creating nginx user";
    useradd nginx -U -M -d / -c 'nginx service user' -s /sbin/nologin;
    # install nginx
    echo "==> Installing Nginx";
    mkdir -p "${SRC_DIR}/nginx";
    curl "http://nginx.org/download/nginx-${NGINX_RELEASE}.tar.gz" \
      | tar -xvz -C "${SRC_DIR}/nginx";
    mkdir -p "${NGINX_PREFIX}";
    pushd "${SRC_DIR}/nginx/nginx-${NGINX_RELEASE}";
    ./configure \
      --user=nginx \
      --group=nginx \
      --prefix=${NGINX_PREFIX} \
      --sbin-path=/usr/sbin/nginx \
      --conf-path=/etc/nginx/nginx.conf \
      --pid-path=/var/run/nginx.pid \
      --lock-path=/var/run/nginx.lock \
      --error-log-path=/var/log/nginx/error.log \
      --http-log-path=/var/log/nginx/access.log \
      --with-http_gzip_static_module \
      --with-http_stub_status_module \
      --with-http_ssl_module \
      --with-pcre \
      --with-http_realip_module;
    make && make install;
    popd;
    # replace default nginx conf
    echo "==> Configuring Nginx";
    mkdir -p "${NGINX_PREFIX}/defaults";
    mkdir -p ${NGINX_PREFIX}/sites-{enabled,available};
    mv ${NGINX_PREFIX}/*.default ${NGINX_PREFIX}/nginx.conf ${NGINX_PREFIX}/defaults;
    cp ${HOME}/files/conf/nginx.conf ${NGINX_PREFIX}/nginx.conf;
    # add service handling
    echo "==> Configuring Nginx service";
    if [[ $(echo "${REDHAT_RELEASE}>=7.0" | bc) == 0 ]]; then
      # redhat release < 7.0
      cp ${HOME}/files/service/nginx.init.d /etc/init.d/nginx;
      chmod 755 /etc/init.d/nginx;
      chown root:root /etc/init.d/nginx;
      chkconfig nginx on;
    else
      # redhat release >= 7.0
      cp ${HOME}/files/service/nginx.systemd /lib/systemd/system/nginx.service;
      chmod 644 /lib/systemd/system/nginx.service;
      chown root:root /lib/systemd/system/nginx.service;
      systemctl daemon-reload;
      systemctl enable nginx;
    fi
    svc_ctrl start nginx;
    # status
    echo '==> OK: nginx has been installed';
    ;;
  uninstall)
    # uninstall nginx
    svc_ctrl stop nginx;
    if [[ $(echo "${REDHAT_RELEASE}>=7.0" | bc) == 0 ]]; then
      # redhat release < 7.0
      chkconfig nginx off;
      rm -f /etc/init.d/nginx;
    else
      # redhat release >= 7.0
      systemctl disable nginx;
      rm -f /lib/systemd/system/nginx.service;
      systemctl daemon-reload;
    fi
    rm -rf ${SRC_DIR}/nginx;
    rm -rf ${NGINX_PREFIX};
    # status
    echo 'OK: nginx has been uninstalled';
    ;;
esac
